### ISSUE TITLE
Numpy bug in more recent versions

### ISSUE THREAD

**Issue by user200000** [bjmorgan/kinisi#69] opened 2024-08-22 14:28 UTC
Hi team,
I'm getting a new error with `numpy 2.1.0` and `python 3.12.4`, which does not occur with  `numpy 1.24.1` and `python 3.11.4`.
When using DiffusionAnalyzer. I get this output for code which would normally work.

AttributeError: module 'numpy' has no attribute 'product'

I think this is probably an incompatibility with the new numpy.

All the best
Sam

**Comment by arm61** [comment] 2024-08-23 06:06
Ahh yeah. This is cause the changed np.product to np.prod. I will sort a fix later today.

**Comment by arm61** [comment] 2024-08-23 08:14
As you can see, I have a PR that will fix this. Once this is merged, you can pip install from GitHub (`pip install git+https://github.com/bjmorgan/kinisi.git`) or simply downgrade NumPy. 

I don't want to make a `1.1.1` release until other features have been added (and when it is a problem caused by NumPy and not a `kinisi` bug).

**Closed** 2024-08-23 08:15 UTC
